package co.edu.uniminuto.ArqSW.MarketPlaceTurismPackage.hibernate;
// Generated 13/03/2014 01:18:27 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CompraServiciosPaquetes generated by hbm2java
 */
public class CompraServiciosPaquetes  implements java.io.Serializable {


     private Integer idCompraServPaqt;
     private Proveedor proveedor;
     private Persona persona;
     private String codigo;
     private Date fechaCompra;
     private String modoPago;
     private double total;
     private double iva;
     private double subTotal;
     private String estado;
     private Set<PaqueteTuristico> paqueteTuristicos = new HashSet<PaqueteTuristico>(0);
     private Set<Servicio> servicios = new HashSet<Servicio>(0);
     private Set<Registro> registros = new HashSet<Registro>(0);

    public CompraServiciosPaquetes() {
    }

	
    public CompraServiciosPaquetes(Proveedor proveedor, Persona persona, String codigo, Date fechaCompra, String modoPago, double total, double iva, double subTotal, String estado) {
        this.proveedor = proveedor;
        this.persona = persona;
        this.codigo = codigo;
        this.fechaCompra = fechaCompra;
        this.modoPago = modoPago;
        this.total = total;
        this.iva = iva;
        this.subTotal = subTotal;
        this.estado = estado;
    }
    public CompraServiciosPaquetes(Proveedor proveedor, Persona persona, String codigo, Date fechaCompra, String modoPago, double total, double iva, double subTotal, String estado, Set<PaqueteTuristico> paqueteTuristicos, Set<Servicio> servicios, Set<Registro> registros) {
       this.proveedor = proveedor;
       this.persona = persona;
       this.codigo = codigo;
       this.fechaCompra = fechaCompra;
       this.modoPago = modoPago;
       this.total = total;
       this.iva = iva;
       this.subTotal = subTotal;
       this.estado = estado;
       this.paqueteTuristicos = paqueteTuristicos;
       this.servicios = servicios;
       this.registros = registros;
    }
   
    public Integer getIdCompraServPaqt() {
        return this.idCompraServPaqt;
    }
    
    public void setIdCompraServPaqt(Integer idCompraServPaqt) {
        this.idCompraServPaqt = idCompraServPaqt;
    }
    public Proveedor getProveedor() {
        return this.proveedor;
    }
    
    public void setProveedor(Proveedor proveedor) {
        this.proveedor = proveedor;
    }
    public Persona getPersona() {
        return this.persona;
    }
    
    public void setPersona(Persona persona) {
        this.persona = persona;
    }
    public String getCodigo() {
        return this.codigo;
    }
    
    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }
    public Date getFechaCompra() {
        return this.fechaCompra;
    }
    
    public void setFechaCompra(Date fechaCompra) {
        this.fechaCompra = fechaCompra;
    }
    public String getModoPago() {
        return this.modoPago;
    }
    
    public void setModoPago(String modoPago) {
        this.modoPago = modoPago;
    }
    public double getTotal() {
        return this.total;
    }
    
    public void setTotal(double total) {
        this.total = total;
    }
    public double getIva() {
        return this.iva;
    }
    
    public void setIva(double iva) {
        this.iva = iva;
    }
    public double getSubTotal() {
        return this.subTotal;
    }
    
    public void setSubTotal(double subTotal) {
        this.subTotal = subTotal;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<PaqueteTuristico> getPaqueteTuristicos() {
        return this.paqueteTuristicos;
    }
    
    public void setPaqueteTuristicos(Set<PaqueteTuristico> paqueteTuristicos) {
        this.paqueteTuristicos = paqueteTuristicos;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }
    public Set<Registro> getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set<Registro> registros) {
        this.registros = registros;
    }




}


