package co.edu.uniminuto.ArqSW.MarketPlaceTurismPackage.hibernate;
// Generated 13/03/2014 01:18:27 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Mensajes generated by hbm2java
 */
public class Mensajes  implements java.io.Serializable {


     private int idMensaje;
     private String enunciado;
     private String emailOrigen;
     private String emailDestino;
     private String mensaje;
     private String tipoMensaje;
     private Set<Persona> personas = new HashSet<Persona>(0);
     private Set<Registro> registros = new HashSet<Registro>(0);

    public Mensajes() {
    }

	
    public Mensajes(int idMensaje, String enunciado, String emailOrigen, String emailDestino, String mensaje, String tipoMensaje) {
        this.idMensaje = idMensaje;
        this.enunciado = enunciado;
        this.emailOrigen = emailOrigen;
        this.emailDestino = emailDestino;
        this.mensaje = mensaje;
        this.tipoMensaje = tipoMensaje;
    }
    public Mensajes(int idMensaje, String enunciado, String emailOrigen, String emailDestino, String mensaje, String tipoMensaje, Set<Persona> personas, Set<Registro> registros) {
       this.idMensaje = idMensaje;
       this.enunciado = enunciado;
       this.emailOrigen = emailOrigen;
       this.emailDestino = emailDestino;
       this.mensaje = mensaje;
       this.tipoMensaje = tipoMensaje;
       this.personas = personas;
       this.registros = registros;
    }
   
    public int getIdMensaje() {
        return this.idMensaje;
    }
    
    public void setIdMensaje(int idMensaje) {
        this.idMensaje = idMensaje;
    }
    public String getEnunciado() {
        return this.enunciado;
    }
    
    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
    }
    public String getEmailOrigen() {
        return this.emailOrigen;
    }
    
    public void setEmailOrigen(String emailOrigen) {
        this.emailOrigen = emailOrigen;
    }
    public String getEmailDestino() {
        return this.emailDestino;
    }
    
    public void setEmailDestino(String emailDestino) {
        this.emailDestino = emailDestino;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public String getTipoMensaje() {
        return this.tipoMensaje;
    }
    
    public void setTipoMensaje(String tipoMensaje) {
        this.tipoMensaje = tipoMensaje;
    }
    public Set<Persona> getPersonas() {
        return this.personas;
    }
    
    public void setPersonas(Set<Persona> personas) {
        this.personas = personas;
    }
    public Set<Registro> getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set<Registro> registros) {
        this.registros = registros;
    }




}


