package co.edu.uniminuto.ArqSW.MarketPlaceTurismPackage.hibernate;
// Generated 13/03/2014 01:18:27 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Persona generated by hbm2java
 */
public class Persona  implements java.io.Serializable {


     private Integer idPersona;
     private TipoPersona tipoPersona;
     private String nombres;
     private String appellidos;
     private String numDocumento;
     private String tipoDocumento;
     private String usuario;
     private String clave;
     private String direccion;
     private String telefono;
     private String telefonoMovil;
     private String email;
     private Boolean verificarUsuario;
     private Date fechaNacimiento;
     private String estado;
     private Set<Proveedor> proveedors = new HashSet<Proveedor>(0);
     private Set<PaqueteTuristico> paqueteTuristicos = new HashSet<PaqueteTuristico>(0);
     private Set<Servicio> servicios = new HashSet<Servicio>(0);
     private Set<Mensajes> mensajeses = new HashSet<Mensajes>(0);
     private Set<CompraServiciosPaquetes> compraServiciosPaqueteses = new HashSet<CompraServiciosPaquetes>(0);

    public Persona() {
    }

	
    public Persona(TipoPersona tipoPersona, String nombres, String appellidos, String numDocumento, String tipoDocumento, String usuario, String clave, String direccion, String telefono, String telefonoMovil, String email, Date fechaNacimiento, String estado) {
        this.tipoPersona = tipoPersona;
        this.nombres = nombres;
        this.appellidos = appellidos;
        this.numDocumento = numDocumento;
        this.tipoDocumento = tipoDocumento;
        this.usuario = usuario;
        this.clave = clave;
        this.direccion = direccion;
        this.telefono = telefono;
        this.telefonoMovil = telefonoMovil;
        this.email = email;
        this.fechaNacimiento = fechaNacimiento;
        this.estado = estado;
    }
    public Persona(TipoPersona tipoPersona, String nombres, String appellidos, String numDocumento, String tipoDocumento, String usuario, String clave, String direccion, String telefono, String telefonoMovil, String email, Boolean verificarUsuario, Date fechaNacimiento, String estado, Set<Proveedor> proveedors, Set<PaqueteTuristico> paqueteTuristicos, Set<Servicio> servicios, Set<Mensajes> mensajeses, Set<CompraServiciosPaquetes> compraServiciosPaqueteses) {
       this.tipoPersona = tipoPersona;
       this.nombres = nombres;
       this.appellidos = appellidos;
       this.numDocumento = numDocumento;
       this.tipoDocumento = tipoDocumento;
       this.usuario = usuario;
       this.clave = clave;
       this.direccion = direccion;
       this.telefono = telefono;
       this.telefonoMovil = telefonoMovil;
       this.email = email;
       this.verificarUsuario = verificarUsuario;
       this.fechaNacimiento = fechaNacimiento;
       this.estado = estado;
       this.proveedors = proveedors;
       this.paqueteTuristicos = paqueteTuristicos;
       this.servicios = servicios;
       this.mensajeses = mensajeses;
       this.compraServiciosPaqueteses = compraServiciosPaqueteses;
    }
   
    public Integer getIdPersona() {
        return this.idPersona;
    }
    
    public void setIdPersona(Integer idPersona) {
        this.idPersona = idPersona;
    }
    public TipoPersona getTipoPersona() {
        return this.tipoPersona;
    }
    
    public void setTipoPersona(TipoPersona tipoPersona) {
        this.tipoPersona = tipoPersona;
    }
    public String getNombres() {
        return this.nombres;
    }
    
    public void setNombres(String nombres) {
        this.nombres = nombres;
    }
    public String getAppellidos() {
        return this.appellidos;
    }
    
    public void setAppellidos(String appellidos) {
        this.appellidos = appellidos;
    }
    public String getNumDocumento() {
        return this.numDocumento;
    }
    
    public void setNumDocumento(String numDocumento) {
        this.numDocumento = numDocumento;
    }
    public String getTipoDocumento() {
        return this.tipoDocumento;
    }
    
    public void setTipoDocumento(String tipoDocumento) {
        this.tipoDocumento = tipoDocumento;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public String getTelefonoMovil() {
        return this.telefonoMovil;
    }
    
    public void setTelefonoMovil(String telefonoMovil) {
        this.telefonoMovil = telefonoMovil;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Boolean getVerificarUsuario() {
        return this.verificarUsuario;
    }
    
    public void setVerificarUsuario(Boolean verificarUsuario) {
        this.verificarUsuario = verificarUsuario;
    }
    public Date getFechaNacimiento() {
        return this.fechaNacimiento;
    }
    
    public void setFechaNacimiento(Date fechaNacimiento) {
        this.fechaNacimiento = fechaNacimiento;
    }
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }
    public Set<Proveedor> getProveedors() {
        return this.proveedors;
    }
    
    public void setProveedors(Set<Proveedor> proveedors) {
        this.proveedors = proveedors;
    }
    public Set<PaqueteTuristico> getPaqueteTuristicos() {
        return this.paqueteTuristicos;
    }
    
    public void setPaqueteTuristicos(Set<PaqueteTuristico> paqueteTuristicos) {
        this.paqueteTuristicos = paqueteTuristicos;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }
    public Set<Mensajes> getMensajeses() {
        return this.mensajeses;
    }
    
    public void setMensajeses(Set<Mensajes> mensajeses) {
        this.mensajeses = mensajeses;
    }
    public Set<CompraServiciosPaquetes> getCompraServiciosPaqueteses() {
        return this.compraServiciosPaqueteses;
    }
    
    public void setCompraServiciosPaqueteses(Set<CompraServiciosPaquetes> compraServiciosPaqueteses) {
        this.compraServiciosPaqueteses = compraServiciosPaqueteses;
    }




}


