package co.edu.uniminuto.ArqSW.MarketPlaceTurismPackage.hibernate;
// Generated 13/03/2014 01:18:27 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoRegistro generated by hbm2java
 */
public class TipoRegistro  implements java.io.Serializable {


     private Integer idTipoRegistro;
     private String tipo;
     private Set<Registro> registros = new HashSet<Registro>(0);

    public TipoRegistro() {
    }

	
    public TipoRegistro(String tipo) {
        this.tipo = tipo;
    }
    public TipoRegistro(String tipo, Set<Registro> registros) {
       this.tipo = tipo;
       this.registros = registros;
    }
   
    public Integer getIdTipoRegistro() {
        return this.idTipoRegistro;
    }
    
    public void setIdTipoRegistro(Integer idTipoRegistro) {
        this.idTipoRegistro = idTipoRegistro;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Registro> getRegistros() {
        return this.registros;
    }
    
    public void setRegistros(Set<Registro> registros) {
        this.registros = registros;
    }




}


