package co.edu.uniminuto.ArqSW.MarketPlaceTurismPackage.hibernate;
// Generated 13/03/2014 01:18:27 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoServicio generated by hbm2java
 */
public class TipoServicio  implements java.io.Serializable {


     private Integer idTipoServicio;
     private String tipo;
     private Set<Servicio> servicios = new HashSet<Servicio>(0);

    public TipoServicio() {
    }

	
    public TipoServicio(String tipo) {
        this.tipo = tipo;
    }
    public TipoServicio(String tipo, Set<Servicio> servicios) {
       this.tipo = tipo;
       this.servicios = servicios;
    }
   
    public Integer getIdTipoServicio() {
        return this.idTipoServicio;
    }
    
    public void setIdTipoServicio(Integer idTipoServicio) {
        this.idTipoServicio = idTipoServicio;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set<Servicio> getServicios() {
        return this.servicios;
    }
    
    public void setServicios(Set<Servicio> servicios) {
        this.servicios = servicios;
    }




}


